$ReportFile = "ASHM_Report_$(Get-Date -Format 'yyyyMMdd_HHmmss').html"
$ReportPath = Join-Path $PSScriptRoot $ReportFile

Write-Host "Generating report..." -ForegroundColor Cyan

$ci = Get-ComputerInfo
$processor = Get-CimInstance Win32_Processor | Select-Object -First 1
$physicalmem = Get-CimInstance Win32_PhysicalMemory
$volumes = Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3"
$processes = Get-Process | Sort-Object CPU -Descending | Select-Object -First 20

$totalRAM = [math]::Round(($physicalmem | Measure-Object -Property Capacity -Sum).Sum / 1GB, 2)

$html = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ASHM Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-950 text-gray-100 p-8">
    <div class="max-w-6xl mx-auto">
        <header class="text-center mb-12">
            <h1 class="text-5xl font-bold mb-4">ASHM System Report</h1>
            <p class="text-gray-400">Generated: $(Get-Date -Format 'F')</p>
            <button onclick="window.print()" class="mt-4 px-6 py-2 bg-blue-600 rounded">Print</button>
        </header>

        <div class="grid grid-cols-2 gap-6 mb-6">
            <div class="bg-gray-800 p-6 rounded-xl">
                <h2 class="text-2xl font-bold mb-4 text-blue-400">System</h2>
                <p><span class="text-gray-400">Manufacturer:</span> $($ci.CsManufacturer)</p>
                <p><span class="text-gray-400">Model:</span> $($ci.CsModel)</p>
                <p><span class="text-gray-400">OS:</span> $($ci.OsName)</p>
            </div>

            <div class="bg-gray-800 p-6 rounded-xl">
                <h2 class="text-2xl font-bold mb-4 text-green-400">CPU</h2>
                <p><span class="text-gray-400">Name:</span> $($processor.Name)</p>
                <p><span class="text-gray-400">Cores:</span> $($processor.NumberOfCores)</p>
                <p><span class="text-gray-400">Threads:</span> $($processor.NumberOfLogicalProcessors)</p>
            </div>
        </div>

        <div class="bg-gray-800 p-6 rounded-xl mb-6">
            <h2 class="text-2xl font-bold mb-4 text-purple-400">RAM (Total: $totalRAM GB)</h2>
            <table class="w-full">
                <thead><tr><th class="text-left">Slot</th><th>Capacity</th><th>Speed</th></tr></thead>
                <tbody>
"@

foreach ($mem in $physicalmem) {
    $html += "<tr><td>$($mem.DeviceLocator)</td><td>$([math]::Round($mem.Capacity/1GB, 2)) GB</td><td>$($mem.Speed) MHz</td></tr>"
}

$html += @"
                </tbody>
            </table>
        </div>

        <div class="bg-gray-800 p-6 rounded-xl mb-6">
            <h2 class="text-2xl font-bold mb-4 text-yellow-400">Storage</h2>
"@

foreach ($vol in $volumes) {
    $size = [math]::Round($vol.Size / 1GB, 2)
    $free = [math]::Round($vol.FreeSpace / 1GB, 2)
    $html += "<p><strong>$($vol.DeviceID)</strong> - $size GB total, $free GB free</p>"
}

$html += @"
        </div>

        <div class="bg-gray-800 p-6 rounded-xl">
            <h2 class="text-2xl font-bold mb-4 text-red-400">Top 20 Processes</h2>
            <table class="w-full text-sm">
                <thead><tr><th class="text-left">Process</th><th>PID</th><th>CPU (s)</th><th>Memory (MB)</th></tr></thead>
                <tbody>
"@

foreach ($proc in $processes) {
    $html += "<tr><td>$($proc.ProcessName)</td><td>$($proc.Id)</td><td>$([math]::Round($proc.CPU, 2))</td><td>$([math]::Round($proc.WorkingSet64/1MB, 2))</td></tr>"
}

$html += @"
                </tbody>
            </table>
        </div>

        <footer class="text-center mt-12 text-gray-600">
            <p>ASHM Report - Generated by PowerShell</p>
        </footer>
    </div>
</body>
</html>
"@

$html | Out-File $ReportPath -Encoding UTF8
Write-Host "Report saved: $ReportPath" -ForegroundColor Green
Start-Process $ReportPath